### ISSUE TITLE
iOS app not opening when integrating Unity app with AltUnityTester

### ISSUE THREAD

**Issue by tanushree1603** [projectxyzio/appium-altunity-plugin#2]
Hi, I am trying to test the Unity Application on iOS device via appium + altUnity tester, but after integrating AltUnity Tester in the Unity Project, whenever I launch the app on the device it's just a black screen and the application closes after 5-6 seconds. This is happening both manually and via automation scripts.

**Comment by jlipps** [comment]
Sounds like the application is somehow not built correctly. Unfortunately the plugin cannot provide support for this situation. If you think the behaviour is due to the altunity tester plugin, then best to contact them about it.
