### ISSUE TITLE
Frequent socket hang up issues observed while executing the test cases

### ISSUE THREAD

**Issue by Mayur5712** [projectxyzio/appium-altunity-plugin#6]
I am trying to execute few test cases on Unity application using Appium + AltUnity plugin. But frequently it is observed that socket getting hang up and tests are not getting executing. 

[appium_altunity.log](https://github.com/headspinio/appium-altunity-plugin/files/9604762/appium_altunity.log)

Kindly check.

**Comment by jlipps** [comment]
> [debug] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.

looks like your app crashed. check logcat for the reason.
